postgresql:
  enabled: false
  install: false
service:
  enabled: true
  name: web
  type: ClusterIP
  url: https://api.pepper.nussman.us/
  externalPort: 3001
  internalPort: 3001
livenessProbe:
  path: "/.well-known/apollo/server-health"
  initialDelaySeconds: 15
  timeoutSeconds: 10
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/.well-known/apollo/server-health"
  initialDelaySeconds: 15
  timeoutSeconds: 10
  scheme: "HTTP"
  probeType: "httpGet"
